### ISSUE TITLE
Thursday Meeting Agenda

### ISSUE THREAD

**Issue by Aveline-art** [100Automations/github-story-points-calculator#22]
## Note to Bonnie

This meeting to get feedback on the proposal is indeterminate. If after reading the [proposal](https://docs.google.com/document/d/1RpdJsCABcd8t2Pqb4gW0ChhwSqXDDiB4ATPEW0jXGkc/edit?skip_itp2_check=true&pli=1#) you feel that a meeting is not needed, feel free to give us feedback asynchronously. Otherwise, our meetings are generally 3PM on Thursdays, but we can also meet anytime Thursday 3PM - 8PM PST. Let me know if that works, and we can prepare a calendar invite! 😸 

### Prework to prep for meeting
- [ ] Prepare research proposal

### New Items
- [ ] Get feedback on [research proposal](https://docs.google.com/document/d/1RpdJsCABcd8t2Pqb4gW0ChhwSqXDDiB4ATPEW0jXGkc/edit?pli=1#heading=h.ra2u7kwniwp4)
- [ ] Get feedback on [research roadmap](https://docs.google.com/document/d/1r5aODB827nXxUHwqxRbkQONBwuZ58LTnijFTidKkIrY/edit?pli=1)
- [ ] Carry over Items to next meeting that don't get addressed

## Note to Bonnie

**Comment by ExperimentsInHonesty** [comment]
Research proposal issue should be linked to this issue.  Please resubmit your request once this issue is complete enough to be reviewed.

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art I have reviewed the research plan and provided some edits.  I also added some comments

In a normal enterprise, I would have not done any research until we had a pilot team use the prototype tool.  Then we would demo/socialize that tool and what the project achieved by it, and then we would ask people to sit for research about it so that we could improve it.

The reason why I would do it that way, is because, otherwise you risk the results from the research coming back as false negative, and then you don't have any funding to move the project forward.

And if we did do research, it would have been to support our hypothesis that the tool is necessary
1. Do you have an objective metric for when to recruit for a new team member in a specific role
2. Have you found yourself suddenly without any designers, or researchers, developers, etc.?
3. Do you know how many weeks of work you have per headcount/per role
4. How much certainty do you have  on number of weeks to deliver a feature?
